openapi: 3.0.3
info:
  title: App Registration Secrets Expiry API
  version: "1.0.0"
  description: |
    API to fetch Microsoft Entra (Azure AD) applications and their secret metadata,
    including application ID, display name, passwordCredentials (client secrets), owners, etc.

servers:
  - url: https://graph.microsoft.com/v1.0
    description: Microsoft Graph v1.0

paths:
  /applications:
    get:
      summary: List applications with secret credentials and owners
      description: |
        Retrieves up to 300 application objects from Microsoft Graph with selected fields: `id`, `appId`, `displayName`, `passwordCredentials`,
        and expands `owners` to get owner details.
      operationId: getApplicationsWithSecretsAndOwners
      parameters:
        - name: $top
          in: query
          description: Number of applications to return (max 300)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 300
            default: 300
        - name: $select
          in: query
          description: Comma-separated list of application fields to select
          required: false
          schema:
            type: string
          example: "id,appId,displayName,passwordCredentials,owners"
        - name: $expand
          in: query
          description: Related entities to expand (e.g. `owners`)
          required: false
          schema:
            type: string
          example: "owners"
      responses:
        "200":
          description: A collection of application objects
          content:
            application/json:
              schema:
                type: object
                properties:
                  "@odata.context":
                    type: string
                    description: OData metadata context
                    example: "https://graph.microsoft.com/v1.0/$metadata#applications(id,appId,displayName,passwordCredentials,owners)"
                  value:
                    type: array
                    description: List of applications
                    items:
                      $ref: "#/components/schemas/Application"
        "400":
          description: Bad request (invalid parameter)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ODataError"
        "401":
          description: Unauthorized (invalid or missing token)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ODataError"
        "403":
          description: Forbidden (insufficient permissions)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ODataError"
        "default":
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ODataError"
      security:
        - oauth2:
          - "https://graph.microsoft.com/.default"

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token
          scopes:
            "https://graph.microsoft.com/.default": Use Microsoft Graph API

  schemas:
    Application:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier (object ID) of the application in Azure AD.
        appId:
          type: string
          description: The Application (client) ID.
        displayName:
          type: string
          description: The display name of the application.
        passwordCredentials:
          type: array
          description: List of client secret credentials associated with the application.
          items:
            $ref: "#/components/schemas/PasswordCredential"
        owners:
          type: array
          description: Owners of the application.
          items:
            $ref: "#/components/schemas/DirectoryObject"
      required:
        - id
        - appId
        - displayName

    PasswordCredential:
      type: object
      properties:
        keyId:
          type: string
          format: uuid
          description: Unique identifier for the password credential.
        displayName:
          type: string
          description: Friendly name of the credential.
        secretText:
          type: string
          description: The actual secret text (only available in certain permission contexts).
        startDateTime:
          type: string
          format: date-time
          description: When the credential becomes valid.
        endDateTime:
          type: string
          format: date-time
          description: When the credential expires.
        customKeyIdentifier:
          type: string
          description: Custom identifier for the key, if set.

    DirectoryObject:
      type: object
      description: Generic directory object (could be user, servicePrincipal, etc.)
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the directory object.
        displayName:
          type: string
          description: Display name of the directory object.
        # You can extend this schema based on more properties (user, SP, etc.)

    ODataError:
      type: object
      description: Standard error format returned by Microsoft Graph
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              description: Error code.
            message:
              type: string
              description: Description of the error.
            innerError:
              type: object
              description: Additional data about the error.
              properties:
                request-id:
                  type: string
                date:
                  type: string

