openapi: 3.0.1
info:
  title: Microsoft Graph – App Registration APIs
  description: Minimal OpenAPI spec for managing Microsoft Graph applications (app registrations) via GET methods.
  version: "1.0"

servers:
  - url: https://graph.microsoft.com/v1.0
    description: Microsoft Graph API v1.0

paths:
  /applications:
    get:
      operationId: listApplications
      summary: List app registrations
      parameters:
        - name: $select
          in: query
          schema:
            type: string
          description: Fields to include (comma-separated)
        - name: $filter
          in: query
          schema:
            type: string
          description: OData filter (e.g., startswith(displayName,'MyApp'))
      responses:
        '200':
          description: List of applications
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        appId:
                          type: string
                        displayName:
                          type: string
                      required:
                        - id
                        - appId
                        - displayName
        default:
          description: Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
                    required:
                      - code
                      - message

  /applications/{appId}:
    get:
      operationId: getApplication
      summary: Get an application by object ID
      parameters:
        - name: appId
          in: path
          required: true
          schema:
            type: string
          description: Object ID of the application
      responses:
        '200':
          description: Application object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  appId:
                    type: string
                  displayName:
                    type: string
                  signInAudience:
                    type: string
                required:
                  - id
                  - appId
                  - displayName
        default:
          description: Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
                    required:
                      - code
                      - message
