openapi: 3.0.0
info:
  title: Graph Applications Secrets Expiry
  description: Returns app registrations and secret expiry info
  version: "1.0.0"

servers:
  - url: https://graph.microsoft.com/v1.0

paths:
  /applications:
    get:
      summary: List applications with their secret expiry info
      operationId: getApplicationsSecrets
      parameters:
        - name: $top
          in: query
          description: Number of items to return
          required: false
          schema:
            type: integer
            default: 300
        - name: $select
          in: query
          description: Fields to select
          required: false
          schema:
            type: string
            default: "id,displayName,passwordCredentials"
      responses:
        "200":
          description: A list of applications
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        displayName:
                          type: string
                        passwordCredentials:
                          type: array
                          items:
                            type: object
                            properties:
                              keyId:
                                type: string
                              displayName:
                                type: string
                              startDateTime:
                                type: string
                                format: date-time
                              endDateTime:
                                type: string
                                format: date-time
