openapi: 3.0.3
info:
  title: App Registration Secrets Expiry API
  version: "1.0.0"
  description: |
    API to fetch Microsoft Entra (Azure AD) applications and their secret metadata,
    including application ID, display name, passwordCredentials (client secrets), owners, etc.

servers:
  - url: https://graph.microsoft.com/v1.0
    description: Microsoft Graph v1.0

paths:
  /applications:
    get:
      summary: List applications with secret credentials and owners
      description: |
        Retrieves up to 300 application objects from Microsoft Graph with selected fields: `id`, `appId`, `displayName`, `passwordCredentials`,
        and expands `owners` to get owner details.
      operationId: getApplicationsWithSecretsAndOwners
      responses:
        "200":
          description: A collection of application objects
          content:
            application/json:
              schema:
                type: object
