openapi: 3.0.3
info:
  title: Microsoft Graph App Registration API
  version: "1.0.0"
  description: |
    API to manage Microsoft Entra (Azure AD) applications (app registrations), including client secrets (passwordCredentials), owners, etc.

servers:
  - url: https://graph.microsoft.com/v1.0
    description: Microsoft Graph v1.0

paths:
  /applications:
    get:
      summary: List applications
      description: List app registrations (Application objects) from Microsoft Graph.
      operationId: listApplications
      parameters:
        - name: $top
          in: query
          description: Max number of items to return
          required: false
          schema:
            type: integer
        - name: $select
          in: query
          description: Fields to select
          required: false
          schema:
            type: string
          example: "id,appId,displayName,passwordCredentials,owners"
        - name: $expand
          in: query
          description: Relationships to expand, e.g. owners
          required: false
          schema:
            type: string
          example: "owners"
      responses:
        "200":
          description: A list of Application objects
          content:
            application/json:
              schema:
                type: object
                properties:
                  "@odata.context":
                    type: string
                  value:
                    type: array
                    items:
                      $ref: "#/components/schemas/Application"
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ODataError"
      security:
        - oauth2:
          - "https://graph.microsoft.com/.default"

    post:
      summary: Create application registration
      description: Create a new Application (app registration) in Entra ID.
      operationId: createApplication
      requestBody:
        description: Application object to create
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplicationCreate"
      responses:
        "201":
          description: Successfully created application
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application"
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ODataError"
      security:
        - oauth2:
          - "https://graph.microsoft.com/.default"

  /applications/{application-id}:
    get:
      summary: Get an application by ID
      description: Retrieve details of a specific Application object.
      operationId: getApplicationById
      parameters:
        - name: application-id
          in: path
          description: The object ID of the application
          required: false
          schema:
            type: string
        - name: $select
          in: query
          description: Fields to select
          required: false
          schema:
            type: string
        - name: $expand
          in: query
          description: Relationships to expand (e.g. owners)
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Application object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application"
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ODataError"
      security:
        - oauth2:
          - "https://graph.microsoft.com/.default"

    patch:
      summary: Update an application
      description: Update properties of an existing Application (app registration).
      operationId: updateApplication
      parameters:
        - name: application-id
          in: path
          description: The object ID of the application
          required: false
          schema:
            type: string
      requestBody:
        description: Application properties to update
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplicationUpdate"
      responses:
        "204":
          description: Application updated (no content)
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ODataError"
      security:
        - oauth2:
          - "https://graph.microsoft.com/.default"

  /applications/{application-id}/owners/$ref:
    post:
      summary: Add an owner to an application
      description: Add an existing directory object (user / service principal) as an owner of the application.
      operationId: addApplicationOwner
      parameters:
        - name: application-id
          in: path
          description: Application (object) ID
          required: false
          schema:
            type: string
      requestBody:
        description: Reference to directory object to be owner
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                "@odata.id":
                  type: string
              required:
                - "@odata.id"
            example:
              "@odata.id": "https://graph.microsoft.com/v1.0/directoryObjects/{owner-id}"
      responses:
        "204":
          description: Owner added successfully
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ODataError"
      security:
        - oauth2:
          - "https://graph.microsoft.com/.default"

  /applications/{application-id}/owners/{owner-id}/$ref:
    delete:
      summary: Remove an owner from application
      description: Remove the owner reference from the application.
      operationId: removeApplicationOwner
      parameters:
        - name: application-id
          in: path
          required: false
          schema:
            type: string
        - name: owner-id
          in: path
          required: false
          schema:
            type: string
      responses:
        "204":
          description: Owner removed
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ODataError"
      security:
        - oauth2:
          - "https://graph.microsoft.com/.default"

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token"
          scopes:
            "https://graph.microsoft.com/.default": Full Graph access

  schemas:
    Application:
      type: object
      properties:
        id:
          type: string
          description: Application object (object ID) — Microsoft Entra ID. :contentReference[oaicite:0]{index=0}
        appId:
          type: string
          description: The unique application (client) ID. :contentReference[oaicite:1]{index=1}
        displayName:
          type: string
        signInAudience:
          type: string
        owners:
          type: array
          items:
            $ref: "#/components/schemas/DirectoryObject"
        passwordCredentials:
          type: array
          items:
            $ref: "#/components/schemas/PasswordCredential"
        keyCredentials:
          type: array
          items:
            $ref: "#/components/schemas/KeyCredential"

    ApplicationCreate:
      type: object
      properties:
        displayName:
          type: string
        signInAudience:
          type: string
        owners:
          type: array
          items:
            type: string
            description: Object IDs (GUID) of directory objects to set as owners
        passwordCredentials:
          type: array
          items:
            $ref: "#/components/schemas/PasswordCredential"
      required:
        - displayName
        - signInAudience

    ApplicationUpdate:
      type: object
      properties:
        displayName:
          type: string
        signInAudience:
          type: string
        passwordCredentials:
          type: array
          items:
            $ref: "#/components/schemas/PasswordCredential"
        keyCredentials:
          type: array
          items:
            $ref: "#/components/schemas/KeyCredential"

    PasswordCredential:
      type: object
      properties:
        keyId:
          type: string
        displayName:
          type: string
        startDateTime:
          type: string
          format: date-time
        endDateTime:
          type: string
          format: date-time
        secretText:
          type: string
        customKeyIdentifier:
          type: string

    KeyCredential:
      type: object
      properties:
        keyId:
          type: string
        displayName:
          type: string
        type:
          type: string
        usage:
          type: string
        customKeyIdentifier:
          type: string
        startDateTime:
          type: string
          format: date-time
        endDateTime:
          type: string
          format: date-time
        key:
          type: string
          description: Base64-encoded key value

    DirectoryObject:
      type: object
      properties:
        id:
          type: string
        displayName:
          type: string

    ODataError:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            innerError:
              type: object
              properties:
                "request-id":
                  type: string
                date:
                  type: string

